[view]
width = 640
height = 480
bpm = 89
dynamic = false
vsync = false


[server]
ip = "127.0.0.1"
port = 3000

[resources]
video_path = "videos"
picture_path = "pictures"


[inputs]
iChannel0 = { type = "Picture", path = "pictures/forest.jpg", width = 640, height = 480}
Hearts = { type = "Picture", path = "pictures/Hearts.png", width = 640, height = 480}
iChannel1 = {type = "Cam", path = "/dev/video0", width = 640, height = 480 }

[[render_chain]]
name = "collage"
inputs = {iChannel0= "iChannel0", iChannel1= "iChannel1", iChannel2= "Hearts"}
vertex_shader = [
    "render_chain/cam/vertex/main.glsl",
]
fragment_shader = [
    "render_chain/cam/fragment/header.glsl",
    "render_chain/cam/fragment/main.glsl",
]